config/routes.rb
Rails.application.routes.draw do
  root "waiter_login#index"

  resources :chefs
  resources :waiters
  resources :items
  resources :order_items

  get "chef_login", to: "chef_login#index"
  post "chef_sign_in", to: "chef_login#sign_in"
  post "chef_sign_out", to: "chef_login#sign_out"
  get "waiter_login", to: "waiter_login#index"
  post "waiter_sign_in", to: "waiter_login#sign_in"
  post "waiter_sign_out", to: "waiter_login#sign_out"
  get "graph", to: "chefs#graph"

  get "chef_forget_password", to: "chef_password_resets#index"
  post "chef_forget_password", to: "chef_password_resets#create"
  get "chef_password_reset_edit", to: "chef_password_resets#edit"
  patch "chef_password_reset_edit", to: "chef_password_resets#update"

  get "waiter_forget_password", to: "waiter_password_reset#index"
  post "waiter_forget_password", to: "waiter_password_reset#create"
  get "waiter_password_reset_edit", to: "waiter_password_reset#edit"
  patch "waiter_password_reset_edit", to: "waiter_password_reset#update"

  get "password", to: "chefs#change_password"
  post "password", to: "chefs#update_password"

  get "waiter_password", to: "waiters#waiter_change_password"
  post "waiter_password", to: "waiters#waiter_update_password"

  #waiter order process
  post "select", to: "waiters#select_item"
  post "cancel", to: "waiters#cancel_item"
  post "confirm", to: "waiters#confirm_order"
  get "orders", to: "waiters#get_orders"
  get "order", to: "waiters#show_order"
  post "pick_order", to: "waiters#pick_order"

  #chef order process
  post "processing", to: "order_items#processing_item"
  post "finished", to: "order_items#finish"
end

app/models/waiter.rb
class Waiter < ApplicationRecord
  has_secure_password
  has_many :orders

  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 30}
  validates :password, presence: true, length: {in: 6..20}, on: :create
  validates :password, confirmation: true, on: :update
  validates :phone, presence: true, length: {in: 9..11}
  validates :address, presence: true, length: {maximum: 250}
  validates :birthday, presence: true
end

app/controllers/waiters_controller.rb
class WaitersController < ApplicationController
  before_action :waiter_authorized, only: [:index, :update, :show, :edit, :waiter_update_password, :select_item, :cancel_item, :confirm_order, :get_orders, :show_order, :pick_order]

  def index
    @coffee = ItemService.get_item_by_category("Coffee")
    @icecream = ItemService.get_item_by_category("Ice Cream")
    @tea = ItemService.get_item_by_category("Tea")
    @cake = ItemService.get_item_by_category("Cake")
    @order_notice = ""
    @orders = Array.new
    if session[:orders]
      @orders = session[:orders]
      @total_price = session[:total_price]
    end
  end

  def new
    @waiter = Waiter.new
  end

  def create
    @waiter = Waiter.new(waiter_params)
    @is_waiter_create = WaiterService.create_waiter(@waiter)

    # check new waiter is create or not
    if @is_waiter_create
      redirect_to root_path
    else
      render :new
    end
  end

  #update waiter profile
  def update
    @waiter = WaiterService.get_waiter_by_id(params[:id])
    @is_waiter_update = WaiterService.update_waiter(@waiter, waiter_params)
    if @is_waiter_update
      redirect_to waiter_path(id: session[:waiter_id])
    else
      render :edit
    end
  end

  #show waiter profile
  def show
    @waiter = WaiterService.get_waiter_by_id(params[:id])
  end

  #edit waiter profile
  def edit
    @waiter = WaiterService.get_waiter_by_id(params[:id])
  end

  #change waiter password
  def waiter_update_password
    if params[:current_password].blank? || params[:password].blank? || params[:confirmation_password].blank?
      if params[:current_password].blank?
        @current = Messages::CURRENT_PASSWORD_REQUIRED
      end
      if params[:password].blank?
        @new = Messages::NEW_PASSWORD_REQUIRED
      end
      if params[:confirmation_password].blank?
        @confirm = Messages::CONFIRM_PASSWORD_REQUIRED
      end
      render :waiter_change_password
    else
      @waiter = WaiterService.get_waiter_by_id(session[:waiter_id])
      if @waiter.authenticate(params[:current_password])
        if params[:password] != params[:confirmation_password]
          @confirm = Messages::CONFIRM_PASSWORD_VALIDATION
          render :waiter_change_password
        else
          @is_update_password = WaiterService.update_password(@waiter, params[:password])
          if @is_update_password
            redirect_to @waiter, alert: Messages::PASSWORD_CHANGE_SUCCESS
          end
        end
      else
        @current = Messages::CURRENT_PASSWORD_VALIDATION
        render :waiter_change_password
      end
    end
  end

  def select_item
    # Initialize the orders array if doesn't exist
    session[:orders] = Array.new unless session[:orders]
    # Initialize total_price if doesn't exist
    session[:total_price] = 0 unless session[:total_price]
    same = false
    item_name = params[:name]
    item_quantity = params[:quantity].to_i
    item_price = item_quantity.to_i * params[:price].to_i
    session[:total_price] += item_price
    if session[:orders]
      session[:orders].each do |order|
        # check the value equal to selected item_name for duplicate item
        if order.value?(item_name)
          same = true
          order.merge!({ "item_name" => item_name, "quantity" => order.values[1] + item_quantity, "price" => order.values[2] + item_price })
        end
      end
    end

    unless same == true
      order = Hash[item_name: item_name, quantity: item_quantity, price: item_price]
      session[:orders].push(order)
    end

    @order_notice = ""
    respond_to do |format|
      format.js
    end
  end

  def cancel_item
    item_name = params[:item_name]
    cancel_item = nil
    for i in 0..session[:orders].length - 1
      session[:orders][i].each do |key, value|
        if (key == "item_name" && value == item_name)
          # make item list to remove from session[:orders]
          cancel_item = i
        end
      end
    end

    @order_notice = ""
    session[:total_price] -= session[:orders][cancel_item].values[2]
    session[:orders].delete_at(cancel_item)
    respond_to do |format|
      format.js
    end
  end

  def confirm_order
    orders = order_params
    waiter = WaiterService.get_waiter_by_id(session[:waiter_id])
    # create waiter's order
    waiter_order = WaiterService.create_order(waiter, "pending", orders[:total_price])
    # create items with that order
    orders[:orders].each do |order|
      WaiterService.create_order_items(waiter_order, order)
    end
    # delete the orders and total_price affter confirm one orders list
    session.delete(:orders)
    session.delete(:total_price)
    # shwo notice about confirm order
    @order_notice = Messages::ORDER_NOTICE
    respond_to do |format|
      format.js
    end
  end

  def get_orders
    @orders = WaiterService.get_waiter_orders(session[:waiter_id])
  end

  def show_order
    @order = OrderService.get_order_by_id(params[:oid])
  end

  def pick_order
    @orders = WaiterService.get_waiter_orders(session[:waiter_id])
    OrderService.update_status(params[:id], "pickup")
    respond_to do |format|
      format.js
    end
  end

  private

  def waiter_params
    params.require(:waiter).permit(:name, :email, :password, :phone, :birthday, :address)
  end

  def order_params
    params.permit(:total_price, :_method, :authenticity_token, :orders => [:item_name, :quantity, :price])
  end
end

app/helpers/waiters_helper.rb
module WaitersHelper
end

app/views/waiters/_order_detail.html.erb
<div class="order-detail">
  <h3 class="order-title">Orders</h3>
  <% unless @orders.blank? %>
    <table class="table">
      <thead class="thead">
        <tr>
          <th width="80">Order Id</th>
          <th width="80">Status</th>
          <th width="300">Order Items</th>
          <th width="100"></th>
          <th width="100"></th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr id="<%= order.id %>">
            <td><%= order.id %></td>
            <td><%= order.status %></td>
            <td>
              <% order.order_items.each do |order_item| %>
                <%= order_item.item_name %>,
              <% end %>
            </td>
            <td><%= link_to "detail", order_path(oid: order.id), class: "btn-detail" %></td>
            <% if order.status == "finished" %>
              <td>
               <%= link_to "pick up", pick_order_path(id: order.id), remote: true, method: :post, class: "btn-pick" %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <h3 class="center">No Order Yet!</h3>
  <% end %>
  <%= link_to "back", waiters_path, class: "btn-back" %>
</div>

app/views/waiters/_orders.html.erb
<div class="aside">
  <h3 class="order-title">Orders</h3>
  <table class="table">
    <thead class="thead">
      <tr>
        <th width="180">Name</th>
        <th width="100">Quantity</th>
        <th width="100">Price(MMK)</th>
      </tr>
    </thead>
    <tbody>
      <% unless orders.length < 1 %>
        <% orders.each do |order| %>
          <tr>
            <% order.each do |key, value| %>
              <td><%= value %></td>
            <% end %>
            <td>
              <a href="<%= cancel_path(item_name: order.values.first) %>" data-remote = true, data-method = "post" class="cancel">
                <i class="fas fa-minus text-secondary"></i>
              </a>
            </td>
          </tr>
        <% end %>
        <tr class="tfoot">
          <td>
            <%= link_to "Confirm Order", confirm_path(total_price: session[:total_price], orders: orders), remote: true, method: "post", class: "btn confirm" %>
          </td>
          <td colspan="2">Total Price - <%= total_price %> MMK</td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% unless order_notice.blank? %>
    <div class="mt-30">
      <%= link_to order_notice, orders_path, class: "order-notice" %>
      <%= link_to "Check the Order in orders tab", orders_path, class: "order-notice" %>
    </div>
  <% end %>
</div>

app/views/waiters/cancel_item.js.erb
$(".cancel").bind("ajax:success", function() {
  console.log("reach");
  $(".aside").replaceWith("<%= j render "orders", order_notice: @order_notice, orders: session[:orders], total_price: session[:total_price] %>")
})

app/views/waiters/confirm_order.js.erb
$(".confirm").bind("ajax:success", () => {
  $(".aside").replaceWith("<%= j render "orders", order_notice: @order_notice, orders: [] %>")
  setTimeout(() => {
    $(".order-notice").fadeOut();
  }, 5000);
})

app/views/waiters/edit.html.erb
<div class="outer-container">
  <div class="container">
    <div class="login-photo">
      <%= image_tag ("login_icons/img_waiter_login.png"), class: "logo", alt: "sign up logo" %>
    </div>
    <h2>Update Profile</h2>
    <%= form_with model: @waiter, class: "login-form" do |f| %>
      <div class="mb-20">
        <%= f.text_field :name, class: "text-box", placeholder: "Enter Name" %>
        <% @waiter.errors.full_messages_for(:name).each do |message| %>
          <div class="text-danger"><%= message %></div>
        <% end %>
      </div>
      <div class="mb-20">
        <%= f.email_field :email, class: "text-box", placeholder: "Enter Email" %>
        <% @waiter.errors.full_messages_for(:email).each do |message| %>
          <div class="text-danger"><%= message %></div>
        <% end %>
      </div>
      <div class="mb-20">
        <%= f.text_field :phone, class: "text-box", placeholder: "Enter Phone" %>
        <% @waiter.errors.full_messages_for(:phone).each do |message| %>
          <div class="text-danger"><%= message %></div>
        <% end %>
      </div>
      <div class="mb-20">
        <%= f.text_field :birthday, onfocus: "(this.type='date')", class: "text-box", placeholder: "Enter Birthday" %>
        <% @waiter.errors.full_messages_for(:birthday).each do |message| %>
          <div class="text-danger"><%= message %></div>
        <% end %>
      </div>
      <div class="mb-20">
        <%= f.text_area :address, class: "text-box", placeholder: "Enter Address" %>
        <% @waiter.errors.full_messages_for(:address).each do |message| %>
          <div class="text-danger"><%= message %></div>
        <% end %>
      </div>
      <div class="submit">
        <%= f.submit "Update", class: "submit-btn" %>
        <%= link_to "Go Back", waiter_path(id: session[:waiter_id]), class: "cancel-btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/waiters/get_orders.html.erb
<div class="item-container">
  <%= render "order_detail", orders: @orders %>
</div>
<script>
    setInterval(() => {
        $(".order-detail").load("/orders .order-detail")
    }, 5000);
</script>

app/views/waiters/index.html.erb
<div class="item-container clearfix">
  <div class="section">
    <% if @coffee.length > 0 %>
      <div>
        <h3 class="hdr"><%= @coffee[0].category.capitalize %></h3>
        <% @coffee.each do |item| %>
          <div class="card">
            <div class="card-body">
              <img src="<%= item.image %>" alt="<%= item.name %>" width="100%" height="225">
              
              <ul class="item-detail">
                <li class="<%= item.id %> item-name" value="<%= item.name %>"><%= item.name %></li>
                <li class="<%= item.id %>" value="<%= item.price %>"><%= item.price %> MMK</li>
                <li>
                  <i class="far fa-minus-square icon"
                    onClick="{down(<%= item.id %>)}"></i>
                  <span id="<%= item.id %>" value="1">1</span>
                  <i class="far fa-plus-square icon" onClick="{up(<%= item.id %>)}"></i>
                </li>
              </ul>

              <a href="" class="btn select" data-remote = true data-method = "POST" onClick="get_url(<%= item.id %>)">Select</a>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
    <% if @icecream.length > 0 %>
      <div>
        <h3 class="hdr"><%= @icecream[0].category.capitalize %></h3>
        <% @icecream.each do |item| %>
          <div class="card">
            <div class="card-body">
              <img src="<%= item.image %>" alt="<%= item.name %>" width="100%" height="220">
              <ul class="item-detail">
                <li class="<%= item.id %> item-name" value="<%= item.name %>"><%= item.name %></li>
                <li class="<%= item.id %>" value="<%= item.price %>"><%= item.price %> MMK</li>
                <li>
                  <i class="far fa-minus-square icon" onClick="{down(<%= item.id %>)}"></i>
                  <span id="<%= item.id %>" value="1">1</span>
                  <i class="far fa-plus-square icon" onClick="{up(<%= item.id %>)}"></i>
                </li>
              </ul>
              <a href="" class="btn select" data-remote = true data-method = "POST" onClick="get_url(<%= item.id %>)">Select</a>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
    <% if @tea.length > 0 %>
      <div>
        <h3 class="hdr"><%= @tea[0].category.capitalize %></h3>
        <% @tea.each do |item| %>
          <div class="card">
            <div class="card-body">
              <img src="<%= item.image %>" alt="<%= item.name %>" width="100%" height="220">
              <ul class="item-detail">
                <li class="<%= item.id %> item-name" value="<%= item.name %>"><%= item.name %></li>
                <li class="<%= item.id %>" value="<%= item.price %>"><%= item.price %> MMK</li>
                <li>
                  <i class="far fa-minus-square icon" onClick="{down(<%= item.id %>)}"></i>
                  <span id="<%= item.id %>" value="1">1</span>
                  <i class="far fa-plus-square icon" onClick="{up(<%= item.id %>)}"></i>
                </li>
              </ul>
              <a href="" class="btn select" data-remote = true data-method = "POST" onClick="get_url(<%= item.id %>)">Select</a>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
    <% if @cake.length > 0 %>
      <div>
        <h3 class="hdr"><%= @cake[0].category.capitalize %></h3>
        <% @cake.each do |item| %>
          <div class="card">
            <div class="card-body">
              <img src="<%= item.image %>" alt="<%= item.name %>" width="100%" height="220">
              <ul class="item-detail">
                <li class="<%= item.id %> item-name" value="<%= item.name %>"><%= item.name %></li>
                <li class="<%= item.id %>" value="<%= item.price %>"><%= item.price %> MMK</li>
                <li>
                  <i class="far fa-minus-square icon" onClick="{down(<%= item.id %>)}"></i>
                  <span id="<%= item.id %>" value="1">1</span>
                  <i class="far fa-plus-square icon" onClick="{up(<%= item.id %>)}"></i>
                </li>
              </ul>
              <a href="" class="btn select" data-remote = true data-method = "POST" onClick="get_url(<%= item.id %>)">Select</a>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= render "orders", orders: @orders, order_notice: @order_notice, total_price: @total_price %>
</div>

<script>
  function up(id) {
    quantity = document.getElementById(id)
    quantity.innerHTML = ++quantity.attributes[1].value;
  }

  function down(id) {
    quantity = document.getElementById(id)
    if (quantity.attributes[1].value == 1) $(`#${id}`).attr("disabled", true);
    else quantity.innerHTML = --quantity.attributes[1].value;
  }

  function get_url(id) {
    values = document.getElementsByClassName(`${id}`);
    quantity = $(`#${id}`).attr("value")
    name = $(values.item(0)).attr("value")
    price = $(values.item(1)).attr("value")
    url = `/select?name=${name}&quantity=${quantity}&price=${price}`
    $(".select").attr("href", url)
  }
    //heightline
(function (factory) {
	if(typeof module === "object" && typeof module.exports === "object") {
		factory(require("jquery"), window, document);
	} else {
		factory(jQuery, window, document);
	}
}(function($, window, document, undefined) {
	$.fn.heightLine = function(){
		var target = this,fontSizeChangeTimer,windowResizeId= Math.random();
		var heightLineObj = {
			op : {
				"maxWidth" : 10000,
				"minWidth" : 0,
				"fontSizeCheck" : false
			},
			setOption : function(op){
				this.op = $.extend(this.op,op);
			},
			destroy : function(){
				target.css("height","");
			},
			create : function(op){
				var self = this,
					maxHeight = 0,
					windowWidth = $(window).width();
				self.setOption(op);
				if( windowWidth<=self.op.maxWidth && windowWidth>=self.op.minWidth ){
					target.each(function(){
						if($(this).outerHeight()>maxHeight){
							maxHeight = $(this).outerHeight();
						}
					}).each(function(){
						var height = maxHeight
								   - parseInt($(this).css("padding-top"))
								   - parseInt($(this).css("padding-bottom"));
						$(this).height(height);
					});
				}
			},
			refresh : function(op){
				this.destroy();
				this.create(op);
			},
			removeEvent :function(){
				$(window).off("resize."+windowResizeId);
				target.off("destroy refresh");
				clearInterval(fontSizeChangeTimer);
			}
		}
		if(typeof arguments[0] === "string" && arguments[0] === "destroy"){
			target.trigger("destroy");
		}else if(typeof arguments[0] === "string" && arguments[0] === "refresh"){
			target.trigger("refresh");
		}else{
			heightLineObj["create"](arguments[0]);
			
			$(window).on("resize."+windowResizeId,function(){
				heightLineObj["refresh"]();
			});

			target.on("destroy",function(){
				heightLineObj["removeEvent"]();
				heightLineObj["destroy"]();
			}).on("refresh",function(){
				heightLineObj["refresh"]();
			});

			if(heightLineObj.op.fontSizeCheck){
				
				if($("#fontSizeChange").length<=0){
					var fontSizeChange = $("<span id='fontSizeChange'></span>").css({
						width:0,
						height:"1em",
						position:"absolute",
						left:0,
						top:0
					}).appendTo("body");
				}
				var defaultFontSize = $("#fontSizeChange").height();
				fontSizeChangeTimer = setInterval(function(){
					if(defaultFontSize != $("#fontSizeChange").height()){
						heightLineObj["refresh"]();
					}
				},100);
			}
		}
		return target;
	}
}));
    $(".item-name").heightLine();


</script>

app/views/waiters/new.html.erb
<div class="container">
  <div class="login-photo">
    <%= image_tag ("login_icons/img_waiter_login.png"), class: "logo", alt: "sign up logo" %>
  </div>
  <h2>Waiter Sign Up</h2>
  <%= render "common/sign_up_form", user: @waiter %>
</div>

app/views/waiters/pick_order.js.erb
$(".btn-pick").bind("ajax:success", function() {
  $(".order-detail").replaceWith("<%= j render "order_detail", orders: @orders %>")
})

app/views/waiters/select_item.js.erb
$(".select").bind("ajax:success", () => {
  $(".aside").replaceWith("<%= j render "orders", order_notice: @order_notice, orders: session[:orders], total_price: session[:total_price] %>")
})

app/views/waiters/show.html.erb
<div class="outer-container">
  <div class="container">
    <h2  class="mb-20">Waiter Profile</h2>
    <div class="login-photo">
      <%= image_tag ("login_icons/img_waiter_login.png"), class: "logo", alt: "sign up logo" %>
    </div>
    <div class="column mb-20">
    <p class="left">Name:</p>
    <span class="right"><%= @waiter.name %></span>
    </div>

    <div class="column mb-20">
    <p class="left">Email:</p>
    <span class="right"><%= @waiter.email %></span>
    </div>

    <div class="column mb-20">
    <p class="left">Phone:</p>
    <span class="right"><%= @waiter.phone %></span>
    </div>
  
    <div class="column mb-20">
    <p class="left">Address:</p>
    <span class="right"><%= @waiter.address %></span>
    </div>

    <div class="column mb-20">
    <p class="left">Birthday:</p>
    <span class="right"><%= @waiter.birthday %></span>
    </div>
   
    <div class="profile-password">
      <%= link_to "Edit Profile", edit_waiter_path(id: session[:waiter_id]) %>
      <%= link_to "Change Password", waiter_password_path %>
    </div>
  </div>
</div>

app/views/waiters/show_order.html.erb
<div class="item-container">
  <div class="detail">
    <h3 class="order-title">Order <%= @order.id %></h3>
    <p class="order-status">Status - <%= @order.status %></p>
    <ul class="order-item-header">
      <li>Name</li>
      <li>Quantity</li>
      <li>Price</li>
    </ul>
    <% @order.order_items.each do |item| %>
      <ul class="order-item">
        <li><%= item.item_name %></li>
        <li><%= item.quantity %></li>
        <li><%= item.price %></li>
      </ul>
    <% end %>
    <div class="order-item-footer clearfix">
      <div class="order-price">
        <span>Total Price - <%= @order.total_price %></span>
      </div>
      <div class="back">
        <%= link_to "back", orders_path, class: "btn-back" %>
      </div>
    </div>
  </div>
</div>
<script>
    setInterval(() => {
        $(".order-status").load("/order?oid=<%= @order.id %> .order-status")
    }, 5000);
</script>

app/views/waiters/waiter_change_password.html.erb
<div class="outer-container">
  <div class="container">
    <h2>Waiter Password Change</h2>
    <%= form_with url: waiter_password_path, class: "login-form", method: :post do |f| %>
      <div class="mb-20">
        <%= f.password_field :current_password, class: "text-box", placeholder: "Enter Current Password" %>
        <% if @current %>
          <span class="error"><%= @current %></span>
        <% end %>
      </div>
      <div class="mb-20">
        <%= f.password_field :password, class: "text-box", placeholder: "Enter New Password" %>
        <% if @new %>
          <span class="error"><%= @new %></span>
        <% end %>
      </div>
      <div class="mb-20">
        <%= f.password_field :confirmation_password, class: "text-box", placeholder: "Confirm  Password" %>
        <% if @confirm %>
          <span class="error"><%= @confirm %></span>
        <% end %>
      </div>
      <div class="submit">
        <%= f.submit "Update", class: "submit-btn" %>
        <%= link_to "Go Back", waiter_path(id: session[:waiter_id]), class: "cancel-btn" %>
      </div>
    <% end %>
  </div>
</div>