config/routes.rb
Rails.application.routes.draw do
  root "waiter_login#index"

  resources :chefs
  resources :waiters
  resources :items
  resources :order_items

  get "chef_login", to: "chef_login#index"
  post "chef_sign_in", to: "chef_login#sign_in"
  post "chef_sign_out", to: "chef_login#sign_out"
  get "waiter_login", to: "waiter_login#index"
  post "waiter_sign_in", to: "waiter_login#sign_in"
  post "waiter_sign_out", to: "waiter_login#sign_out"
  get "graph", to: "chefs#graph"

  get "chef_forget_password", to: "chef_password_resets#index"
  post "chef_forget_password", to: "chef_password_resets#create"
  get "chef_password_reset_edit", to: "chef_password_resets#edit"
  patch "chef_password_reset_edit", to: "chef_password_resets#update"

  get "waiter_forget_password", to: "waiter_password_reset#index"
  post "waiter_forget_password", to: "waiter_password_reset#create"
  get "waiter_password_reset_edit", to: "waiter_password_reset#edit"
  patch "waiter_password_reset_edit", to: "waiter_password_reset#update"

  get "password", to: "chefs#change_password"
  post "password", to: "chefs#update_password"

  get "waiter_password", to: "waiters#waiter_change_password"
  post "waiter_password", to: "waiters#waiter_update_password"

  #waiter order process
  post "select", to: "waiters#select_item"
  post "cancel", to: "waiters#cancel_item"
  post "confirm", to: "waiters#confirm_order"
  get "orders", to: "waiters#get_orders"
  get "order", to: "waiters#show_order"
  post "pick_order", to: "waiters#pick_order"

  #chef order process
  post "processing", to: "order_items#processing_item"
  post "finished", to: "order_items#finish"
end

app/controllers/waiter_login_controller.rb
class WaiterLoginController < ApplicationController
  before_action :is_waiter, only: [:index]

  def sign_in
    @waiter = WaiterService.find_by_email(params[:email])

    # check if authenticate or not
    if @waiter && @waiter.authenticate(params[:password])
      session[:waiter_id] = @waiter.id
      puts "loggined in #{waiters_path}"
      redirect_to waiters_path
    else
      redirect_to root_path, notice: Messages::LOGIN_ERR
    end
  end

  def sign_out
    session.clear
    redirect_to root_path
  end
end

app/helpers/waiter_login_helper.rb
module WaiterLoginHelper
end

app/views/waiter_login/index.html.erb
<div class="container">

  <div class="login-photo">
    <%= image_tag ("login_icons/img_waiter_login.png"), class: "logo", alt: "waiter login icon" %>
  </div>
  <h2>Watier Login</h2>

  <%= form_with url: waiter_sign_in_path,  class: "login-form" do |form| %>
    <div class="mb-20">
      <%= form.text_field :email, class: "text-box", placeholder: "Enter Email", required: true %>
    </div>

    <div class="mb-20">
      <%= form.password_field :password, class: "text-box", placeholder: "Enter Password", required: true %>
    </div>

    <div class="login-link">
      <%= link_to "Login As Chef?", chef_login_path, class: "links" %>
      <%= link_to "Forgot Password?", waiter_forget_password_path, class: "links" %>
    </div>

    <p class="create-acc">Do not have any account? <%= link_to "Sign Up Account", new_waiter_path, class: "links" %></p>
    <div class="submit"><%= form.submit "Sign In", class: "submit-btn" %></div>

  <% end %>

</div>