config/routes.rb
Rails.application.routes.draw do
  root "waiter_login#index"

  resources :chefs
  resources :waiters
  resources :items
  resources :order_items

  get "chef_login", to: "chef_login#index"
  post "chef_sign_in", to: "chef_login#sign_in"
  post "chef_sign_out", to: "chef_login#sign_out"
  get "waiter_login", to: "waiter_login#index"
  post "waiter_sign_in", to: "waiter_login#sign_in"
  post "waiter_sign_out", to: "waiter_login#sign_out"
  get "graph", to: "chefs#graph"

  get "chef_forget_password", to: "chef_password_resets#index"
  post "chef_forget_password", to: "chef_password_resets#create"
  get "chef_password_reset_edit", to: "chef_password_resets#edit"
  patch "chef_password_reset_edit", to: "chef_password_resets#update"

  get "waiter_forget_password", to: "waiter_password_reset#index"
  post "waiter_forget_password", to: "waiter_password_reset#create"
  get "waiter_password_reset_edit", to: "waiter_password_reset#edit"
  patch "waiter_password_reset_edit", to: "waiter_password_reset#update"

  get "password", to: "chefs#change_password"
  post "password", to: "chefs#update_password"

  get "waiter_password", to: "waiters#waiter_change_password"
  post "waiter_password", to: "waiters#waiter_update_password"

  #waiter order process
  post "select", to: "waiters#select_item"
  post "cancel", to: "waiters#cancel_item"
  post "confirm", to: "waiters#confirm_order"
  get "orders", to: "waiters#get_orders"
  get "order", to: "waiters#show_order"
  post "pick_order", to: "waiters#pick_order"

  #chef order process
  post "processing", to: "order_items#processing_item"
  post "finished", to: "order_items#finish"
end

app/views/layouts/_header.html.erb
<div class="nav">
  <a><h1 class="ttl-logo">SCM Cafe</h1></a>
   <div class="menu-btn">
    <span></span>
    <span></span>
    <span></span>
  </div>
  <div class="menu menu-sp">
  <ul>
    <% if session[:waiter_id] || session[:chef_id] %>
      <li>
        <%= link_to "Order Lists", session[:waiter_id] ? orders_path : order_items_path,
                    class: "link #{"is-active" if current_page?(controller: "order_items", action: "index") || current_page?("http://localhost:3000/orders")}" %>
      </li>
      <li>
        <%= link_to "Item List", session[:waiter_id] ? waiters_path : items_path,
                    class: "link #{"is-active" if current_page?(controller: "items", action: "index") || current_page?(controller: "waiters", action: "index")}" %>
      </li>
      <li>
        <%= link_to "Profile",
                    session[:waiter_id] ? waiter_path(id: session[:waiter_id]) : chef_path(id: session[:chef_id]),
                    class: "link #{"is-active" if current_page?("http://localhost:3000/chefs/#{session[:chef_id]}") || current_page?("http://localhost:3000/waiters/#{session[:waiter_id]}")}" %>
      </li>
      <li><%= link_to "Graph", graph_path, class: "link #{"is-active" if current_page?(controller: "chefs", action: "graph")}" %></li>
      <li>
        <%= link_to "Log Out", session[:waiter_id] ? waiter_sign_out_path : chef_sign_out_path, class: "link", method: :post %>
      </li>
    <% end %>
  </ul>
</div>
</div>
<script>
//menu JS
$(document).ready(function () {
    $('.menu-btn').click(function () {
        if ($(this).hasClass('active')) {
            $(this).removeClass('active');
        }
        else {
            $(this).addClass('active');
        }
        $('.menu-sp').animate({ width: 'toggle' });
    });
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CafeOrderingSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Font Awesome -->
    <link rel="stylesheet"
    href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
    integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm"
    crossorigin="anonymous">
    <%= stylesheet_link_tag "application", params[:controller], media: "all", 'data-turbolinks-track': "reload" %>
    <!-- Jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% elsif alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <% if session[:waiter_id] || session[:chef_id] %>
      <%= render "layouts/header" %>
    <% end %>
    <%= yield %>
  </body>
</html>